### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by readnotify** [perlancar/perl-ColorTheme#1]
Says this right at the start:
```
{
  string  => "ffff00",
  number  => "00ffff",
  comma   => "",
  brace   => "",
  bracket => "",
  null    => "ff0000",
  true    => "00ff00",
  false   => "008000",
}
```
but without any hint or clue as to where that goes or how to use it to change anything.

Contains verbose and exciting mention of all kinds of other things we can do, which all point to off-topic things like "DefHash" and so-on, but nothing which shows any examples of how to use any of it!

**Comment by perlancar** [comment]
The Description section is actually the start, not the Glossary section. Added a pointer (commit 4c23c31).
